config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes do
    resources :reviews
  end

  root 'recipes#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	belongs_to :user
	mount_uploader :image, ImageUploader
	has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :recipe
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @reviews = @recipe.reviews
  end

  def new
    @recipe = current_user.recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      UserMailer.newrecipe_email(@user.id).deliver!
      redirect_to recipes_path
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipes_path
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      redirect_to recipes_path
    end
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :items, :process, :image)    
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @recipe = Recipe.find(params[:recipe_id])
    @reviews= @recipe.reviews
  end

  def show
    @recipe = Recipe.find(params[:recipe_id])
    @review = @recipe.reviews.find(params[:id])
  end

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @review = @recipe.reviews.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @reviews = @recipe.reviews.new(save)
    if @recipe.save
      redirect_to recipe_path(recipe)
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def save
    params.require(:review).permit(:comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FoodReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%if user_signed_in? %>
		<nav class="navbar navbar-inverse">
			<ul class="nav nav-pills">
				<li style="display:inline"><%= link_to 'Home', recipes_path %></li>
				<li><%= link_to 'New', new_recipe_path %></li>
				<li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
			</ul>	
		</nav>
	<% else %>
		<nav class="navbar navbar-inverse">
			<ul class="nav nav-pills">
				<li><%= link_to 'Home', recipes_path %></li>
				<li><%= link_to 'Log In', new_user_session_path %></li>
				<li><%= link_to 'Sign Up', new_user_registration_path %></li>
			</ul>
		</nav>
	<% end %>
<%= yield %>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

</body>
</html>

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/delete.html.erb
<h1>Recipes#delete</h1>
<p>Find me in app/views/recipes/delete.html.erb</p>

app/views/recipes/destroy.html.erb
<h1>Recipes#destroy</h1>
<p>Find me in app/views/recipes/destroy.html.erb</p>

app/views/recipes/edit.html.erb
<%= form_for(@recipe) do |f| %>
	<%= f.label ("Recipe") %>
	<%= f.text_field :title %><br>
	<%= f.label ("Ingredients") %>
	<%= f.text_area :items %><br>
	<%= f.label ("Procedure") %>
	<%= f.text_area :process %><br>
	<%= submit_tag ("Save") %>
<% end %>

app/views/recipes/index.html.erb
<div class="row">
	<% @recipes.each do |recipe| %>
		<div class="col-sm-6 col-md-4">
			<strong><%= recipe.title %></strong>
			<div class="thumbnail">
				<%= image_tag recipe.image_url, size:"150x150" %>
			</div>
			<div class="caption">
				<%= recipe.items %><br>
				<%= recipe.process %><br>
				<%= link_to 'View', recipe_path(recipe) %>
				<%= link_to 'edit', edit_recipe_path(recipe) %>
				<%= link_to 'delete', recipe, method: :delete, data: {confirm: 'Delete recipe???'} %>
				<%= link_to 'add comment', new_recipe_review_path(recipe) %>
			</div>
	<% end %>
		</div>
</div>

app/views/recipes/new.html.erb
<%= form_for :recipe, url: {action: 'create'}, :html => {:multipart => true} do |f| %>
	<p>
		<%= f.label ("Title:") %>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label ("Ingredients:") %>
		<%= f.text_area :items %>
	</p>
	<p>
		<%= f.label ("Procedure:") %>
		<%= f.text_area :process %>
	</p>
	<p>
		<%= f.file_field :image %>	
	</p>
	<br>
	<%= submit_tag ("Save") %>
<% end %>

app/views/recipes/show.html.erb
<p>
	<%= image_tag @recipe.image_url, size:"200x200" %>
</p>
<p>
	<strong>Recipe:</strong>
	<%= @recipe.title %>
</p>
<p>
	<strong>Ingredients:</strong>
	<%= @recipe.items %>
</p>
<p>
	<strong>Procedure:</strong>
	<%= @recipe.process %>
</p>
<p>
	<strong>Reviews:</strong>
	<% @reviews.each do |review| %>
		<%= review.comment %>
	<% end %>
</p>
<p>
	<%= form_for :review, :url => recipe_reviews_path do |f| %>
	<%= f.label :comment %>
	<%= f.text_area :comment %><br>
	<%= submit_tag ("Save") %>
	<% end %>
</p>

app/views/recipes/update.html.erb
<h1>Recipes#update</h1>
<p>Find me in app/views/recipes/update.html.erb</p>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

<%= form_for :review, url: {action: 'create'} do |f| %>
	<%= f.label :comment %>
	<%= f.text_area :comment %><br>
	<%= submit_tag ("Save") %>
<% end %>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>